image: 683422241496.dkr.ecr.us-east-1.amazonaws.com/cd-rails-base:latest

before_script:
  # - 'apt-get update && apt-get install -y redis-server'
  # - /etc/init.d/redis-server start
  # - service redis-server status
  # - redis-cli ping
  # - touch log/application.log
  - touch log/app.log
  - touch log/db.log
  - touch log/test.log
  - rename 's/.example//' config/settings/*.example
  - rename 's/.example//' config/*.example
  - bundle install --jobs $(nproc) --path=/cache/bundler
  - mysqladmin -uroot -h mysql create mycloud_test
  - RAILS_ENV=test bundle exec rake db:migrate db:seed


cucumber:
  services:
    - mysql:5.6
  script:
    - mkdir test-plans
    - xvfb-run -a bundle exec cucumber --format html --out test-plans/report.html
    # - xvfb-run -a bundle exec cucumber features/PCP_001/ -r features --format html --out test-plans/report_PCP001.html
    # - xvfb-run -a bundle exec cucumber features/PCP_002/ -r features --format html --out test-plans/report_PCP003.html
    # - xvfb-run -a bundle exec cucumber features/PCP_003/ -r features --format html --out test-plans/report_PCP003.html
    # - xvfb-run -a bundle exec cucumber features/PCP_004/ -r features --format html --out test-plans/report_PCP004.html
    # - xvfb-run -a bundle exec cucumber features/PCP_005/ -r features --format html --out test-plans/report_PCP005.html
    # - xvfb-run -a bundle exec cucumber features/PCP_006/ -r features --format html --out test-plans/report_PCP006.html
    # - xvfb-run -a bundle exec cucumber features/REST/ -r features --format html --out test-plans/report_REST.html
    # - xvfb-run -a bundle exec cucumber features/Service/ -r features --format html --out test-plans/report_Service.html
    - yard config load_plugins true
    - yardoc 'app/**/*.rb' 'features/**/*.rb' 'features/**/*.feature'
  artifacts:
    paths:
      - test-plans/
      - doc
  only:
    - develop
    - feature/20160329-1-test-new-gitlab-ci-setting