default_app_logger: &app_logger
  name          : application
  level         : DEBUG
  trace         : 'true'
  outputters    : 
    - app_log_server
    - app_rolling_file

default_db_logger: &db_logger
  name          : database
  level         : DEBUG
  trace         : 'true'
  outputters    :
    - db_log_server
    - db_rolling_file

default_fluent_post_outputter: &fluent_post_outputter
  type: FluentPostOutputter
  name: log_server
  tag: personal_cloud.default
  host: '10.107.10.174'

default_date_file_outputter: &rolling_file_outputter
  type: RollingFileOutputter
  name: rolling_file
  maxsize: 5120000000
  max_backups: 1
  dirname: "log"
  filename: "db.log"
  formatter:
    date_pattern: '%H:%M:%S:%L'
    pattern     : '%d %l: %m'
    type        : PatternFormatter

# default_date_file_outputter: &date_file_outputter
#   type: DateFileOutputter
#   name: db_log
#   dirname: "log"
#   filename: "db.log"
#   formatter:
#     date_pattern: '%H:%M:%S:%L'
#     pattern     : '%d %l: %m'
#     type        : PatternFormatter

# config for each enviornment
production:
  log4r_config:
    loggers:
    - <<: *app_logger
    - <<: *db_logger
    outputters:
    - <<: *fluent_post_outputter
      name: app_log_server
      tag: personal_cloud.app.production
    - <<: *fluent_post_outputter
      name: db_log_server
      tag: personal_cloud.db.production
    - <<: *rolling_file_outputter
      name: app_rolling_file
      filename: "log/app.log"
    - <<: *rolling_file_outputter
      name: db_rolling_file
      filename: "log/db.log"

beta:
  log4r_config:
    loggers:
    - <<: *app_logger
    - <<: *db_logger
    outputters:
    - <<: *fluent_post_outputter
      name: app_log_server
      tag: personal_cloud.app.beta
    - <<: *fluent_post_outputter
      name: db_log_server
      tag: personal_cloud.db.beta
    - <<: *rolling_file_outputter
      name: app_rolling_file
      filename: "log/app.log"
    - <<: *rolling_file_outputter
      name: db_rolling_file
      filename: "log/db.log"

alpha:
  log4r_config:
    loggers:
    - <<: *app_logger
    - <<: *db_logger
    outputters:
    - <<: *fluent_post_outputter
      name: app_log_server
      tag: personal_cloud.app.alpha
    - <<: *fluent_post_outputter
      name: db_log_server
      tag: personal_cloud.db.alpha
    - <<: *rolling_file_outputter
      name: app_rolling_file
      filename: "log/app.log"
    - <<: *rolling_file_outputter
      name: db_rolling_file
      filename: "log/db.log"

