default_app_logger: &app_logger
  name          : application
  level         : DEBUG
  trace         : 'true'
  outputters    : 
    - log_server

default_db_logger: &db_logger
  name          : database
  level         : DEBUG
  trace         : 'true'
  outputters    : 
    - db_log

default_fluent_post_outputter: &fluent_post_outputter
  type: FluentPostOutputter
  name: log_server
  tag: personal_cloud.default
  host: '10.107.10.174'

default_date_file_outputter: &date_file_outputter
  type: DateFileOutputter
  name: db_log
  dirname: "log"
  filename: "db.log"
  formatter:
    date_pattern: '%H:%M:%S:%L'
    pattern     : '%d %l: %m'
    type        : PatternFormatter

production:
  log4r_config:
    loggers:
    - <<: *app_logger
      level         : INFO
    - <<: *db_logger
      level         : INFO
    outputters:
    - <<: *fluent_post_outputter
      tag: personal_cloud.production
    - <<: *date_file_outputter

beta:
  log4r_config:
    loggers:
    - <<: *app_logger
    - <<: *db_logger
    outputters:
    - <<: *fluent_post_outputter
      tag: personal_cloud.beta
    - <<: *date_file_outputter

alpha:
  log4r_config:
    loggers:
    - <<: *app_logger
    - <<: *db_logger
    outputters:
    - <<: *fluent_post_outputter
      tag: personal_cloud.alpha
    - <<: *date_file_outputter

