log4r_config:
  # define all loggers:
  loggers:
    - name          : application
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - log_server

    - name          : database
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - db_log

  # define all outputters (incl. formatters)
  outputters:
  - type: FluentPostOutputter
    name: log_server
    tag: myapp
    host: '10.106.30.227'
  - type: DateFileOutputter
    name: app_log
    dirname: "log"
    filename: "app.log"
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %X{context} %l: %m'
      type        : PatternFormatter
  - type: DateFileOutputter
    name: db_log
    dirname: "log"
    filename: "db.log"
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m'
      type        : PatternFormatter