files:
  devise.en.yml: "https://docs.google.com/spreadsheets/d/13URXscDajqg1b8hdP6v8NGy_7R6icL0vzypi61ToveA/pub?gid=0&single=true&output=csv"
  en.yml: "https://docs.google.com/spreadsheets/d/1TfW1vcVcwhCXRZZiu8DZkF9D1JcQrdA3bjIsqo8o1lQ/pub?gid=0&single=true&output=csv"
  upnp_description.en.yml: "https://docs.google.com/spreadsheets/d/1cRUweMZ42Z44OFA1PZpc6CL4jq7YxFLRdA00AE-T_Ek/pub?gid=2128347434&single=true&output=csv"
  user.en.yml: "https://docs.google.com/spreadsheets/d/1R0uzNc6JaDotA0lG-SxX4r6e6Njo6NukbuWa1TMxPbQ/pub?gid=0&single=true&output=csv"
  mailer.en.yml: "https://docs.google.com/spreadsheets/d/1cRUweMZ42Z44OFA1PZpc6CL4jq7YxFLRdA00AE-T_Ek/pub?gid=623378773&single=true&output=csv"