development:
  version: 'V.B.20150617_01'
  suffix: '-dev'
test:
  version: 'V.B.20150617_01'
  suffix: '-testing'
staging:
  version: 'V.B.20150617_01'
  suffix: '-alpha'
production:
  version: 'V.B.20150617_01'
  suffix: '-release'
