magic_number: 890980
version: V.B.20140926_03
xmpp:
  server: localhost
  device_rescource_id: device
  admin:
    account   : bot01
    password  : 1234
  bots:
    - bot01@localhost
    - bot02@localhost
    - bot03@localhost
    - bot04@localhost
    - bot05@localhost
    - bot06@localhost
    - bot07@localhost
    - bot08@localhost
  nodes:
    - 172.31.25.84
environments:
  api_domain: 'api_alpha.pcloud.ecoworkinc.com'
  portal_domain: 'pcloud.dev'
  paperclip:
    default:
      storage: :s3
      s3_credentials:
        bucket: 'mycloud-beta'
        access_key_id: 'AKIAJRREKZSZGSF3DPWQ'
        secret_access_key: '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'
    attachment:
      default:
        url: ':mycloud-beta.s3.amazonaws.com'
        s3_host_name: 's3-external-1.amazonaws.com'
        path: '/:class/:attachment/:id_partition/:style/:filename'
  sqs:
    name: 'personal_cloud_queue_test'
    attributes:
      access_key_id: 'AKIAIOKGDAZ2CJ7QW3HQ'
      secret_access_key: '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'
      region: 'us-west-2'
  ddns: pcloud.ecoworkinc.com
  cdn: 'https://d3k0gq7ryrjfe4.cloudfront.net'
  filter_list:
    - api
    - www
    - dns
    - ddns
    - upnp
    - blog
    - zyxel
    - store
    - host
    - support
    - service
    - services
oauth:
  facebook_app_id: 678292992243317
  facebook_secret: 386ec08a3d700466bac2c66641c71e4b
  google_app_id: 14580324123-25ourkvv3ppvh4c1uph5gacjj6lq7q51.apps.googleusercontent.com
  google_secret: XXG2i7MwFpRvOn6hd4gg9nWv
recaptcha:
  config.public_key: '6LelPvUSAAAAAHQP8AccRDnMO0ETmgmtY-okFr95'
  config.private_key: '6LelPvUSAAAAAGdYfFVdxTPayPH1cQG5jIpoDqcj'