magic_number: 890980
api:
  stun_ip_addresses:
    - ec2-54-85-72-999.compute-1.amazonaws.com
    - ec2-107-21-4-999.compute-1.amazonaws.com
xmpp:
  server: localhost
  device_resource_id: device
  bots:
    - bot01@localhost
    - bot02@localhost
    - bot03@localhost
    - bot04@localhost
    - bot05@localhost
    - bot06@localhost
    - bot07@localhost
    - bot08@localhost
  nodes:
    - ec2-54-85-72-129.compute-1.amazonaws.com
    - ec2-107-21-4-229.compute-1.amazonaws.com
environments:
  name: 'alpha'
  api_domain: 'localhost'
  portal_domain: 'localhost'
  ga_tracker: 'UA-57135359-1'
  paperclip:
    default:
      storage: :s3
      s3_credentials:
        bucket: 's3-pcloud-test'
        access_key_id: 'AKIAJRREKZSZGSF3DPWQ'
        secret_access_key: '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'
    attachment:
      default:
        s3_host_name: 's3-us-west-2.amazonaws.com'
        path: '/:class/:attachment/:id_partition/:style/:filename'
  sqs:
    name: 'PCloud-Alpha-Bot-Jobs-Test'
    attributes:
      access_key_id: 'AKIAIULMFADPJ7NNOGIQ'
      secret_access_key: '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'
      region: 'us-east-1'
  ddns: pcloud.ecoworkinc.com
  cdn: 'https://d3k0gq7ryrjfe4.cloudfront.net'
  filter_list:
    - api
    - www
    - dns
    - ddns
    - upnp
    - blog
    - zyxel
    - store
    - host
    - support
    - service
    - services
oauth:
  facebook_app_id: 1417673045203233
  facebook_secret: cbef4be0ae0d9fce4662e10731bbd812
  google_app_id: 14580324123-25ourkvv3ppvh4c1uph5gacjj6lq7q51.apps.googleusercontent.com
  google_secret: XXG2i7MwFpRvOn6hd4gg9nWv
recaptcha:
  config:
    public_key: '6LelPvUSAAAAAHQP8AccRDnMO0ETmgmtY-okFr95'
    private_key: '6LelPvUSAAAAAGdYfFVdxTPayPH1cQG5jIpoDqcj'
redis:
  web_host: '127.0.0.1'
  xmpp_host: '127.0.0.1'
  port: 6379