magic_number: 890980
xmpp:
  server: localhost
  device_resource_id: device
  bots:
    - bot01@localhost
    - bot02@localhost
    - bot03@localhost
    - bot04@localhost
    - bot05@localhost
    - bot06@localhost
    - bot07@localhost
    - bot08@localhost
  nodes:
    - ec2-54-85-72-129.compute-1.amazonaws.com
    - ec2-107-21-4-229.compute-1.amazonaws.com
environments:
  public_key:
    example_serial: |
                -----BEGIN PUBLIC KEY-----
                MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3QNj4mwsBv49Zh7pDi1P
                Dr0/HH9koD0J2rgLtUcr6vfoHiVrITSjPUMg0dK7ipRCajBbVJ+9Yq9kfs7ocBJj
                inhWqSrnzNUznswqPTSw2aj0Xxau8f60GFmx74qDGPQeVkWWumXCZYdahUJOKADv
                2rvbcqsggd2pJE6hACuC7xco9W4Arvf+nNazrZjWwRy2y5hSjPe6IN8Y2gmufwRW
                8J9nzU1T72oxjMYbPMN38t2TAMTUIAZ08soRPdSj4Aj2hp/1cn4W7FECyJ3s+DGf
                lHS96YqAPHsifnqi/KsqIZ3c5xxCMsfuG7RFz8LNmf/GDxhotwktC965qgNxbr8x
                TNMreraAfKabnjLaVkpNIVqlICjbZFTvPnwG1pJmnlluO0BkYp6t+f7d3/InQPyA
                kkiYoWmrj2yXwVTajWyRGSaD5T6rA/XIctZojrjDhjFoj9cnLBFScJLKTmqPOIOZ
                KSL4uiKvrfqaYTO3ss8ggKvLceBSRx1dpmA3VwlvO4j5LEuL1S4dlXgyDGm8X/GS
                UcQ5kaPmqc6fCvbHuII+cnu+Kjbq18MSo4kjibnl2sfCCG7G2KsXsP5CDFHNWPr7
                JaOXLp7oumqvxSRklTwgl8etJBaKV7hV7tc8yEzmjxgbgqnC+H+wfpdQvgd1ZK3e
                sHwEn3OD7zEps14uS7Uc17MCAwEAAQ==
                -----END PUBLIC KEY-----
  name: 'alpha'
  api_domain: 'localhost'
  portal_domain: 'localhost'
  ga_tracker: 'UA-57135359-1'
  paperclip:
    default:
      storage: :s3
      s3_credentials:
        bucket: 's3-pcloud-test'
        access_key_id: 'AKIAJRREKZSZGSF3DPWQ'
        secret_access_key: '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'
    attachment:
      default:
        s3_host_name: 's3-us-west-2.amazonaws.com'
        path: '/:class/:attachment/:id_partition/:style/:filename'
  sqs:
    name: 'PCloud-Alpha-Bot-Jobs-Test'
    attributes:
      access_key_id: 'AKIAIULMFADPJ7NNOGIQ'
      secret_access_key: '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'
      region: 'us-east-1'
  ddns: pcloud.ecoworkinc.com
  cdn: 'https://d3k0gq7ryrjfe4.cloudfront.net'
  filter_list:
    - api
    - www
    - dns
    - ddns
    - upnp
    - blog
    - zyxel
    - store
    - host
    - support
    - service
    - services
oauth:
  facebook_app_id: 678292992243317
  facebook_secret: 386ec08a3d700466bac2c66641c71e4b
  google_app_id: 14580324123-25ourkvv3ppvh4c1uph5gacjj6lq7q51.apps.googleusercontent.com
  google_secret: XXG2i7MwFpRvOn6hd4gg9nWv
recaptcha:
  config:
    public_key: '6LelPvUSAAAAAHQP8AccRDnMO0ETmgmtY-okFr95'
    private_key: '6LelPvUSAAAAAGdYfFVdxTPayPH1cQG5jIpoDqcj'
redis:
  web_host: '127.0.0.1'
  xmpp_host: '127.0.0.1'
  port: 6379