magic_number: 0800
xmpp:
  server : xmpp.pcloud.ecoworkinc.com
  admin  :
    account   : admin
    password  : abcdefg
  bots : 
    - bot1@xmpp.pcloud.ecoworkinc.com/robot
environments:
  paperclip:
    default:
      storage: :s3
      s3_credentials: 
        bucket: 's3-pcloud-test'
        access_key_id: 'AKIAJS52YFZUARWCSMVQ'
        secret_access_key: 'vsys5QRBqdhzurgBfR8NgKP1zHojPcF'
    attachment:
      default:
        url: ':s3-pcloud-test.s3.amazonaws.com'
        s3_host_name: 's3-us-west-2.amazonaws.com'
        path: '/:class/:attachment/:id_partition/:style/:filename'
  sqs:
    name: 'personal_cloud_queue_test'
    attributes:
      access_key_id: 'AKIAIOKGDAZ2CJ7QW3HQ'
      secret_access_key: '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'
      region: 'us-west-2'