magic_number: 0800
xmpp:
  server : xmpp.pcloud.ecoworkinc.com
  admin  :
    account   : admin
    password  : abcdefg
  bots : 
    - bot01@xmpp.pcloud.ecoworkinc.com
    - bot02@xmpp.pcloud.ecoworkinc.com
    - bot03@xmpp.pcloud.ecoworkinc.com
    - bot04@xmpp.pcloud.ecoworkinc.com
    - bot05@xmpp.pcloud.ecoworkinc.com
    - bot06@xmpp.pcloud.ecoworkinc.com